// Code generated by vine. DO NOT EDIT.
package runtime

const Namespace = "go.vine"


const (
	ApiserverName = "go.vine.service.apiserver"
	AuthName = "go.vine.service.auth"
)

var (
	ApiserverId = "744f4422-694b-4ebf-a22c-5fed009c70fc"
	AuthId = "bab996ea-f3b3-44dc-8268-3365ce90aa7c"
)

var (
	GitTag    string
	GitCommit string
	BuildDate string
	GetVersion = func() string {
		v := GitTag
		if GitCommit != "" {
			v += "-" + GitCommit
		}
		if BuildDate != "" {
			v += "-" + BuildDate
		}
		if v == "" {
			return "latest"
		}
		return v
	}
)
