// Code generated by proto-gen-vine. DO NOT EDIT.
// source: github.com/vine-io/services/proto/service/apiserver/v1/apiserver.proto

package apiserverv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	client "github.com/vine-io/vine/core/client"
	server "github.com/vine-io/vine/core/server"
	api "github.com/vine-io/vine/lib/api"
	apipb "github.com/vine-io/vine/proto/apis/api"
	openapi "github.com/vine-io/vine/proto/apis/openapi"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// API Endpoints for ApiserverService service
func NewApiserverServiceEndpoints() []*apipb.Endpoint {
	return []*apipb.Endpoint{
		&apipb.Endpoint{
			Name:        "ApiserverService.GetIP",
			Description: "ApiserverService.GetIP",
			Path:        []string{"/api/v1/getIP"},
			Method:      []string{"GET"},
			Body:        "*",
			Handler:     "rpc",
		},
		&apipb.Endpoint{
			Name:        "ApiserverService.Healthz",
			Description: "ApiserverService.Healthz",
			Path:        []string{"/api/v1/healthz"},
			Method:      []string{"GET"},
			Body:        "*",
			Handler:     "rpc",
		},
	}
}

// Swagger OpenAPI 3.0 for ApiserverService service
func NewApiserverServiceOpenAPI() *openapi.OpenAPI {
	return &openapi.OpenAPI{
		Openapi: "3.0.1",
		Info: &openapi.OpenAPIInfo{
			Title:       "ApiserverServiceService",
			Description: "OpenAPI3.0 for ApiserverService",
			Version:     "v1.0.0",
		},
		Servers: []*openapi.OpenAPIServer{},
		Tags: []*openapi.OpenAPITag{
			&openapi.OpenAPITag{
				Name:        "ApiserverService",
				Description: "OpenAPI3.0 for ApiserverService",
			},
		},
		Paths: map[string]*openapi.OpenAPIPath{
			"/api/v1/getIP": &openapi.OpenAPIPath{
				Get: &openapi.OpenAPIPathDocs{
					Tags:        []string{"ApiserverService"},
					Description: "ApiserverService GetIP",
					OperationId: "ApiserverServiceGetIP",
					Parameters:  []*openapi.PathParameters{},
					Responses: map[string]*openapi.PathResponse{
						"200": &openapi.PathResponse{
							Description: "successful response (stream response)",
							Content: &openapi.PathRequestBodyContent{
								ApplicationJson: &openapi.ApplicationContent{
									Schema: &openapi.Schema{Ref: "#/components/schemas/v1.IPRsp"},
								},
							},
						},
					},
					Security: []*openapi.PathSecurity{},
				},
			},
			"/api/v1/healthz": &openapi.OpenAPIPath{
				Get: &openapi.OpenAPIPathDocs{
					Tags:        []string{"ApiserverService"},
					Description: "ApiserverService Healthz",
					OperationId: "ApiserverServiceHealthz",
					Parameters:  []*openapi.PathParameters{},
					Responses: map[string]*openapi.PathResponse{
						"200": &openapi.PathResponse{
							Description: "successful response (stream response)",
							Content: &openapi.PathRequestBodyContent{
								ApplicationJson: &openapi.ApplicationContent{
									Schema: &openapi.Schema{Ref: "#/components/schemas/v1.Empty"},
								},
							},
						},
					},
					Security: []*openapi.PathSecurity{},
				},
			},
		},
		Components: &openapi.OpenAPIComponents{
			SecuritySchemes: &openapi.SecuritySchemes{},
			Schemas: map[string]*openapi.Model{
				"v1.Empty": &openapi.Model{
					Type:       "object",
					Properties: map[string]*openapi.Schema{},
				},
				"v1.IPRsp": &openapi.Model{
					Type: "object",
					Properties: map[string]*openapi.Schema{
						"addr": &openapi.Schema{
							Type: "string",
						},
					},
				},
			},
		},
	}
}

// Client API for ApiserverService service
// +gen:openapi
type ApiserverService interface {
	// +gen:get=/api/v1/getIP
	GetIP(ctx context.Context, in *Empty, opts ...client.CallOption) (*IPRsp, error)
	// +gen:get=/api/v1/healthz
	Healthz(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error)
}

type apiserverService struct {
	c    client.Client
	name string
}

func NewApiserverService(name string, c client.Client) ApiserverService {
	return &apiserverService{
		c:    c,
		name: name,
	}
}

func (c *apiserverService) GetIP(ctx context.Context, in *Empty, opts ...client.CallOption) (*IPRsp, error) {
	req := c.c.NewRequest(c.name, "ApiserverService.GetIP", in)
	out := new(IPRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiserverService) Healthz(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error) {
	req := c.c.NewRequest(c.name, "ApiserverService.Healthz", in)
	out := new(Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiserverService service
// +gen:openapi
type ApiserverServiceHandler interface {
	// +gen:get=/api/v1/getIP
	GetIP(context.Context, *Empty, *IPRsp) error
	// +gen:get=/api/v1/healthz
	Healthz(context.Context, *Empty, *Empty) error
}

func RegisterApiserverServiceHandler(s server.Server, hdlr ApiserverServiceHandler, opts ...server.HandlerOption) error {
	type apiserverServiceImpl interface {
		GetIP(ctx context.Context, in *Empty, out *IPRsp) error
		Healthz(ctx context.Context, in *Empty, out *Empty) error
	}
	type ApiserverService struct {
		apiserverServiceImpl
	}
	h := &apiserverServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&apipb.Endpoint{
		Name:        "ApiserverService.GetIP",
		Description: "ApiserverService.GetIP",
		Path:        []string{"/api/v1/getIP"},
		Method:      []string{"GET"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&apipb.Endpoint{
		Name:        "ApiserverService.Healthz",
		Description: "ApiserverService.Healthz",
		Path:        []string{"/api/v1/healthz"},
		Method:      []string{"GET"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, server.OpenAPIHandler(NewApiserverServiceOpenAPI()))
	return s.Handle(s.NewHandler(&ApiserverService{h}, opts...))
}

type apiserverServiceHandler struct {
	ApiserverServiceHandler
}

func (h *apiserverServiceHandler) GetIP(ctx context.Context, in *Empty, out *IPRsp) error {
	return h.ApiserverServiceHandler.GetIP(ctx, in, out)
}

func (h *apiserverServiceHandler) Healthz(ctx context.Context, in *Empty, out *Empty) error {
	return h.ApiserverServiceHandler.Healthz(ctx, in, out)
}
