// Code generated by proto-gen-validator. DO NOT EDIT.
// source: github.com/vine-io/services/api/service/apiserver/v1/apiserver.proto

package apiserverv1

import (
	is "github.com/vine-io/vine/util/is"
)

func (m *Empty) Validate() error {
	return m.ValidateE("")
}

func (m *Empty) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *IPRsp) Validate() error {
	return m.ValidateE("")
}

func (m *IPRsp) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}
