// Code generated by proto-gen-vine. DO NOT EDIT.
// source: github.com/vine-io/services/proto/service/auth/v1/auth.proto

package authv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	client "github.com/vine-io/vine/core/client"
	server "github.com/vine-io/vine/core/server"
	api "github.com/vine-io/vine/lib/api"
	apipb "github.com/vine-io/vine/proto/apis/api"
	openapi "github.com/vine-io/vine/proto/apis/openapi"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// API Endpoints for AuthService service
func NewAuthServiceEndpoints() []*apipb.Endpoint {
	return []*apipb.Endpoint{
		&apipb.Endpoint{
			Name:        "AuthService.Call",
			Description: "AuthService.Call",
			Path:        []string{"/auth/v1/auth/Call"},
			Method:      []string{"POST"},
			Body:        "*",
			Handler:     "rpc",
		},
	}
}

// Swagger OpenAPI 3.0 for AuthService service
func NewAuthServiceOpenAPI() *openapi.OpenAPI {
	return &openapi.OpenAPI{
		Openapi: "3.0.1",
		Info: &openapi.OpenAPIInfo{
			Title:       "AuthServiceService",
			Description: "OpenAPI3.0 for AuthService",
			Version:     "v1.0.0",
		},
		Servers: []*openapi.OpenAPIServer{},
		Tags: []*openapi.OpenAPITag{
			&openapi.OpenAPITag{
				Name:        "AuthService",
				Description: "OpenAPI3.0 for AuthService",
			},
		},
		Paths: map[string]*openapi.OpenAPIPath{
			"/auth/v1/auth/Call": &openapi.OpenAPIPath{
				Post: &openapi.OpenAPIPathDocs{
					Tags:        []string{"AuthService"},
					Description: "AuthService Call",
					OperationId: "AuthServiceCall",
					RequestBody: &openapi.PathRequestBody{
						Description: "Call Request",
						Content: &openapi.PathRequestBodyContent{
							ApplicationJson: &openapi.ApplicationContent{
								Schema: &openapi.Schema{
									Ref: "#/components/schemas/v1.Request",
								},
							},
						},
					},
					Responses: map[string]*openapi.PathResponse{
						"200": &openapi.PathResponse{
							Description: "successful response (stream response)",
							Content: &openapi.PathRequestBodyContent{
								ApplicationJson: &openapi.ApplicationContent{
									Schema: &openapi.Schema{Ref: "#/components/schemas/v1.Response"},
								},
							},
						},
					},
					Security: []*openapi.PathSecurity{},
				},
			},
		},
		Components: &openapi.OpenAPIComponents{
			SecuritySchemes: &openapi.SecuritySchemes{},
			Schemas: map[string]*openapi.Model{
				"v1.Request": &openapi.Model{
					Type: "object",
					Properties: map[string]*openapi.Schema{
						"name": &openapi.Schema{
							Type: "string",
						},
					},
					Required: []string{"name"},
				},
				"v1.Response": &openapi.Model{
					Type: "object",
					Properties: map[string]*openapi.Schema{
						"msg": &openapi.Schema{
							Type: "string",
						},
					},
				},
			},
		},
	}
}

// Client API for AuthService service
// +gen:openapi
type AuthService interface {
	// +gen:post=/auth/v1/auth/Call
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (AuthService_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (AuthService_PingPongService, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AuthService.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (AuthService_StreamService, error) {
	req := c.c.NewRequest(c.name, "AuthService.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &authServiceStream{stream}, nil
}

type AuthService_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type authServiceStream struct {
	stream client.Stream
}

func (x *authServiceStream) Close() error {
	return x.stream.Close()
}

func (x *authServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authService) PingPong(ctx context.Context, opts ...client.CallOption) (AuthService_PingPongService, error) {
	req := c.c.NewRequest(c.name, "AuthService.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &authServicePingPong{stream}, nil
}

type AuthService_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type authServicePingPong struct {
	stream client.Stream
}

func (x *authServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *authServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *authServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *authServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for AuthService service
// +gen:openapi
type AuthServiceHandler interface {
	// +gen:post=/auth/v1/auth/Call
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, AuthService_StreamStream) error
	PingPong(context.Context, AuthService_PingPongStream) error
}

func RegisterAuthServiceHandler(s server.Server, hdlr AuthServiceHandler, opts ...server.HandlerOption) error {
	type authServiceImpl interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type AuthService struct {
		authServiceImpl
	}
	h := &authServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&apipb.Endpoint{
		Name:        "AuthService.Call",
		Description: "AuthService.Call",
		Path:        []string{"/auth/v1/auth/Call"},
		Method:      []string{"POST"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, server.OpenAPIHandler(NewAuthServiceOpenAPI()))
	return s.Handle(s.NewHandler(&AuthService{h}, opts...))
}

type authServiceHandler struct {
	AuthServiceHandler
}

func (h *authServiceHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AuthServiceHandler.Call(ctx, in, out)
}

func (h *authServiceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AuthServiceHandler.Stream(ctx, m, &authServiceStreamStream{stream})
}

type AuthService_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type authServiceStreamStream struct {
	stream server.Stream
}

func (x *authServiceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *authServiceStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authServiceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authServiceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authServiceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *authServiceHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AuthServiceHandler.PingPong(ctx, &authServicePingPongStream{stream})
}

type AuthService_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type authServicePingPongStream struct {
	stream server.Stream
}

func (x *authServicePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *authServicePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authServicePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authServicePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authServicePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *authServicePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
